// ─── Module Definitions (UI metadata) ───────────────────────────────────────

const MODULE_DEFS = {
  // ── Oscillators ──
  OscA: {
    label: "OscA",
    category: "oscillator",
    color: "#c22",
    inputs: ["Sync"],
    outputs: ["Out", "Slv"],
    modInputs: ["PitchMod1", "PitchMod2", "FmMod", "PWMod"],
    description: "Master oscillator - Full-featured with FM, PW, sync",
  },
  OscB: {
    label: "OscB",
    category: "oscillator",
    color: "#c33",
    inputs: [],
    outputs: ["Out", "Slv"],
    modInputs: ["PitchMod1", "PitchMod2", "FmMod"],
    description: "Oscillator B - Classic analog waveforms with FM",
  },
  OscC: {
    label: "OscC",
    category: "oscillator",
    color: "#c55",
    inputs: [],
    outputs: ["Out", "Slv"],
    modInputs: ["PitchMod", "FMA", "AM"],
    description: "Oscillator C - Sine with AM and FMA",
  },
  Noise: {
    label: "Noise",
    category: "oscillator",
    color: "#888",
    inputs: [],
    outputs: ["Out"],
    modInputs: [],
    description: "White/Pink noise generator",
  },
  DrumSynth: {
    label: "Drum",
    category: "oscillator",
    color: "#c66",
    inputs: [],
    outputs: ["Out"],
    modInputs: ["Trig", "VelMod", "PitchMod"],
    description: "Drum synth - Dual osc, multimode noise filter, bend",
  },
  FormantOsc: {
    label: "Formant",
    category: "oscillator",
    color: "#c55",
    inputs: [],
    outputs: ["Out", "Slv"],
    modInputs: ["PitchMod1", "PitchMod2"],
    description: "Formant oscillator - Vowel synthesis with slave output",
  },
  MasterOsc: {
    label: "MstOsc",
    category: "oscillator",
    color: "#d44",
    inputs: [],
    outputs: ["Slv"],
    modInputs: ["PitchMod1", "PitchMod2"],
    description: "Master oscillator - Pitch controller for slaves",
  },
  OscSlvA: {
    label: "SlvA",
    category: "oscillator",
    color: "#b33",
    inputs: ["Mst", "Sync"],
    outputs: ["Out"],
    modInputs: ["FMA", "AM"],
    description: "Slave osc A - 4 waveforms, sync, FM & AM",
  },
  OscSlvB: {
    label: "SlvB",
    category: "oscillator",
    color: "#b44",
    inputs: ["Mst"],
    outputs: ["Out"],
    modInputs: ["PwMod"],
    description: "Slave osc B - Square/Pulse with PW",
  },
  OscSlvC: {
    label: "SlvC",
    category: "oscillator",
    color: "#b55",
    inputs: ["Mst"],
    outputs: ["Out"],
    modInputs: ["FMA"],
    description: "Slave osc C - Sawtooth",
  },
  OscSlvD: {
    label: "SlvD",
    category: "oscillator",
    color: "#b66",
    inputs: ["Mst"],
    outputs: ["Out"],
    modInputs: ["FMA"],
    description: "Slave osc D - Triangle",
  },
  OscSlvE: {
    label: "SlvE",
    category: "oscillator",
    color: "#b77",
    inputs: ["Mst"],
    outputs: ["Out"],
    modInputs: ["FMA", "AM"],
    description: "Slave osc E - Sine, FM & AM",
  },
  OscSlvFM: {
    label: "SlvFM",
    category: "oscillator",
    color: "#b88",
    inputs: ["Mst", "Sync"],
    outputs: ["Out"],
    modInputs: ["FMB"],
    description: "Slave FM osc - Sine, FM-optimized, sync",
  },
  OscSineBank: {
    label: "SinBnk",
    category: "oscillator",
    color: "#c44",
    inputs: ["Mst", "Sync", "MixIn"],
    outputs: ["Out"],
    modInputs: ["AM1", "AM2", "AM3", "AM4", "AM5", "AM6"],
    description: "6-oscillator sine bank with sync and mix-in",
  },
  SpectralOsc: {
    label: "Spectral",
    category: "oscillator",
    color: "#c66",
    inputs: [],
    outputs: ["Out", "Slv"],
    modInputs: ["PitchMod1", "PitchMod2", "FMA", "ShapeMod"],
    description: "Spectral oscillator - Additive partial stack",
  },
  PercOsc: {
    label: "PercOsc",
    category: "oscillator",
    color: "#c77",
    inputs: [],
    outputs: ["Out"],
    modInputs: ["Trig", "Amp", "PitchMod"],
    description: "Percussive oscillator - Click and punch",
  },
  // ── Filters ──
  Filter: {
    label: "Filter",
    category: "filter",
    color: "#2a7",
    inputs: ["In"],
    outputs: ["Out"],
    modInputs: ["FreqMod", "ResMod"],
    description: "Multi-mode filter with resonance",
  },
  FilterC: {
    label: "FiltC",
    category: "filter",
    color: "#2b8",
    inputs: ["In"],
    outputs: ["LP", "BP", "HP"],
    modInputs: ["FreqMod", "ResMod"],
    description: "Static 3-output multimode filter",
  },
  FilterE: {
    label: "FiltE",
    category: "filter",
    color: "#2c9",
    inputs: ["In"],
    outputs: ["Out"],
    modInputs: ["FreqMod1", "FreqMod2", "ResMod"],
    description: "Dynamic filter with slope select",
  },
  // ── Modulators ──
  Envelope: {
    label: "Env",
    category: "modulator",
    color: "#c80",
    inputs: ["In"],
    outputs: ["Out"],
    modInputs: [],
    description: "ADSR Envelope generator",
  },
  ADSREnv: {
    label: "ADSR",
    category: "modulator",
    color: "#c90",
    inputs: ["In"],
    outputs: ["Out"],
    modInputs: ["Gate", "Retrig"],
    description: "Enhanced ADSR with curve control",
    paramRows: [{ knobs: ["attack", "decay", "sustain", "release"] }],
  },
  LFO: {
    label: "LFO",
    category: "modulator",
    color: "#c60",
    inputs: [],
    outputs: ["Out"],
    modInputs: [],
    description: "Low frequency oscillator for modulation",
  },
  LFOA: {
    label: "LFOA",
    category: "modulator",
    color: "#c70",
    inputs: [],
    outputs: ["Out", "SlvOut"],
    modInputs: ["Rst", "RateMod"],
    description: "Enhanced LFO with waveform select",
  },
  ClkGen: {
    label: "Clock",
    category: "modulator",
    color: "#c95",
    inputs: [],
    outputs: ["Clk24", "Clk4", "Sync"],
    modInputs: [],
    description: "Clock generator with BPM control",
  },
  RandomGen: {
    label: "Random",
    category: "modulator",
    color: "#c65",
    inputs: [],
    outputs: ["Out"],
    modInputs: [],
    description: "Random signal generator",
  },
  PortamentoA: {
    label: "Porta",
    category: "modulator",
    color: "#c75",
    inputs: ["In"],
    outputs: ["Out"],
    modInputs: [],
    description: "Portamento / glide processor",
  },
  EventSeq: {
    label: "EvtSeq",
    category: "modulator",
    color: "#ca5",
    inputs: ["Clk", "Rst"],
    outputs: ["Out1", "Out2"],
    modInputs: [],
    description: "16-step event/trigger sequencer",
    customUIHeight: 70,
  },
  CtrlSeq: {
    label: "CtrlSq",
    category: "modulator",
    color: "#cb6",
    inputs: ["Clk", "Rst"],
    outputs: ["Out"],
    modInputs: [],
    description: "16-step control value sequencer",
    customUIHeight: 80,
  },
  NoteSeqA: {
    label: "NtSeqA",
    category: "modulator",
    color: "#cc7",
    inputs: ["Clk", "Rst"],
    outputs: ["Note", "Gate"],
    modInputs: [],
    description: "16-step note sequencer with gate",
    customUIHeight: 100,
  },
  NoteSeqB: {
    label: "NtSeqB",
    category: "modulator",
    color: "#cd8",
    inputs: ["Clk", "Rst"],
    outputs: ["Note", "Gate"],
    modInputs: [],
    description: "16-step piano roll sequencer",
    customUIHeight: 120,
  },
  // ── Level ──
  Amplifier: {
    label: "Amp",
    category: "level",
    color: "#66a",
    inputs: ["In"],
    outputs: ["Out"],
    modInputs: ["GainMod"],
    description: "Voltage controlled amplifier",
  },
  Mixer3: {
    label: "Mix3",
    category: "level",
    color: "#669",
    inputs: ["In1", "In2", "In3"],
    outputs: ["Out"],
    modInputs: [],
    description: "3-channel mixer",
  },
  Mixer8: {
    label: "Mix8",
    category: "level",
    color: "#668",
    inputs: ["In1", "In2", "In3", "In4", "In5", "In6", "In7", "In8"],
    outputs: ["Out"],
    modInputs: [],
    description: "8-channel mixer",
  },
  XFade: {
    label: "X-Fade",
    category: "level",
    color: "#66b",
    inputs: ["InA", "InB"],
    outputs: ["Out"],
    modInputs: ["FadeMod"],
    description: "Crossfader between two inputs",
  },
  Panner: {
    label: "Pan",
    category: "level",
    color: "#6a6",
    inputs: ["In"],
    outputs: ["Out"],
    modInputs: ["PanMod"],
    description: "Stereo panner",
  },
  // ── Effects ──
  Delay: {
    label: "Delay",
    category: "effect",
    color: "#4899bb",
    inputs: ["In"],
    outputs: ["Out"],
    modInputs: [],
    description: "Delay effect with feedback",
  },
  ShortDelay: {
    label: "ShDly",
    category: "effect",
    color: "#489abb",
    inputs: ["In"],
    outputs: ["Out"],
    modInputs: ["TimeMod"],
    description: "Short delay for flanging (0-2.65ms)",
  },
  Chorus: {
    label: "Chorus",
    category: "effect",
    color: "#48a9bb",
    inputs: ["In"],
    outputs: ["Out"],
    modInputs: [],
    description: "Stereo chorus effect",
  },
  Shaper: {
    label: "Shaper",
    category: "effect",
    color: "#4a80bb",
    inputs: ["In"],
    outputs: ["Out"],
    modInputs: [],
    description: "Waveshaper with drive control",
  },
  // ── I/O ──
  Keyboard: {
    label: "Keys",
    category: "io",
    color: "#777",
    inputs: [],
    outputs: ["Note", "Gate", "Vel"],
    modInputs: [],
    description: "Keyboard - Play notes with keys",
    customUIHeight: 55,
  },
  Output: {
    label: "Out",
    category: "io",
    color: "#555",
    inputs: ["InL", "InR"],
    outputs: [],
    modInputs: [],
    description: "Master audio output",
  },
};

const CATEGORIES = [
  { key: "oscillator", label: "Oscillators", modules: ["MasterOsc", "OscA", "OscB", "OscC", "SpectralOsc", "FormantOsc", "OscSlvA", "OscSlvB", "OscSlvC", "OscSlvD", "OscSlvE", "OscSineBank", "OscSlvFM", "Noise", "PercOsc", "DrumSynth"] },
  { key: "filter", label: "Filters", modules: ["Filter", "FilterC", "FilterE"] },
  { key: "modulator", label: "Modulators", modules: ["Envelope", "ADSREnv", "LFO", "LFOA", "ClkGen", "RandomGen", "PortamentoA", "EventSeq", "CtrlSeq", "NoteSeqA", "NoteSeqB"] },
  { key: "level", label: "Level", modules: ["Amplifier", "Mixer3", "Mixer8", "XFade", "Panner"] },
  { key: "effect", label: "Effects", modules: ["Delay", "ShortDelay", "Chorus", "Shaper"] },
  { key: "io", label: "I/O", modules: ["Keyboard", "Output"] },
];

export { MODULE_DEFS, CATEGORIES };
